package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0



/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer branchId;
     private Location location;
     private Employee employee;
     private String branchName;
     private String branchCode;
     private String branchPostalAddress;
     private String branchPostalCode;
     private String branchMail;
     private Boolean active;
     private String uuid;

    public Branch() {
    }

	
    public Branch(Location location, Employee employee, String branchName, String branchCode, String branchPostalAddress, String branchPostalCode, String branchMail, String uuid) {
        this.location = location;
        this.employee = employee;
        this.branchName = branchName;
        this.branchCode = branchCode;
        this.branchPostalAddress = branchPostalAddress;
        this.branchPostalCode = branchPostalCode;
        this.branchMail = branchMail;
        this.uuid = uuid;
    }
    public Branch(Location location, Employee employee, String branchName, String branchCode, String branchPostalAddress, String branchPostalCode, String branchMail, Boolean active, String uuid) {
       this.location = location;
       this.employee = employee;
       this.branchName = branchName;
       this.branchCode = branchCode;
       this.branchPostalAddress = branchPostalAddress;
       this.branchPostalCode = branchPostalCode;
       this.branchMail = branchMail;
       this.active = active;
       this.uuid = uuid;
    }
   
    public Integer getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    public String getBranchPostalAddress() {
        return this.branchPostalAddress;
    }
    
    public void setBranchPostalAddress(String branchPostalAddress) {
        this.branchPostalAddress = branchPostalAddress;
    }
    public String getBranchPostalCode() {
        return this.branchPostalCode;
    }
    
    public void setBranchPostalCode(String branchPostalCode) {
        this.branchPostalCode = branchPostalCode;
    }
    public String getBranchMail() {
        return this.branchMail;
    }
    
    public void setBranchMail(String branchMail) {
        this.branchMail = branchMail;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


