package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0



/**
 * CaseMap generated by hbm2java
 */
public class CaseMap  implements java.io.Serializable {


     private Integer caseMapId;
     private CaseClasses caseClassesByParentId;
     private CaseClasses caseClassesByChildId;
     private String uuid;

    public CaseMap() {
    }

	
    public CaseMap(String uuid) {
        this.uuid = uuid;
    }
    public CaseMap(CaseClasses caseClassesByParentId, CaseClasses caseClassesByChildId, String uuid) {
       this.caseClassesByParentId = caseClassesByParentId;
       this.caseClassesByChildId = caseClassesByChildId;
       this.uuid = uuid;
    }
   
    public Integer getCaseMapId() {
        return this.caseMapId;
    }
    
    public void setCaseMapId(Integer caseMapId) {
        this.caseMapId = caseMapId;
    }
    public CaseClasses getCaseClassesByParentId() {
        return this.caseClassesByParentId;
    }
    
    public void setCaseClassesByParentId(CaseClasses caseClassesByParentId) {
        this.caseClassesByParentId = caseClassesByParentId;
    }
    public CaseClasses getCaseClassesByChildId() {
        return this.caseClassesByChildId;
    }
    
    public void setCaseClassesByChildId(CaseClasses caseClassesByChildId) {
        this.caseClassesByChildId = caseClassesByChildId;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


