package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0



/**
 * ClientConfig generated by hbm2java
 */
public class ClientConfig  implements java.io.Serializable {


     private Integer clientTypeId;
     private String clientTypeName;
     private String clientTypeCode;
     private Boolean active;
     private String uuid;

    public ClientConfig() {
    }

	
    public ClientConfig(String clientTypeName, String clientTypeCode, String uuid) {
        this.clientTypeName = clientTypeName;
        this.clientTypeCode = clientTypeCode;
        this.uuid = uuid;
    }
    public ClientConfig(String clientTypeName, String clientTypeCode, Boolean active, String uuid) {
       this.clientTypeName = clientTypeName;
       this.clientTypeCode = clientTypeCode;
       this.active = active;
       this.uuid = uuid;
    }
   
    public Integer getClientTypeId() {
        return this.clientTypeId;
    }
    
    public void setClientTypeId(Integer clientTypeId) {
        this.clientTypeId = clientTypeId;
    }
    public String getClientTypeName() {
        return this.clientTypeName;
    }
    
    public void setClientTypeName(String clientTypeName) {
        this.clientTypeName = clientTypeName;
    }
    public String getClientTypeCode() {
        return this.clientTypeCode;
    }
    
    public void setClientTypeCode(String clientTypeCode) {
        this.clientTypeCode = clientTypeCode;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


