package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ClientPayment generated by hbm2java
 */
public class ClientPayment  implements java.io.Serializable {


     private Integer paymentId;
     private User user;
     private File file;
     private int amountPaid;
     private String receiptNumber;
     private Date datePaid;
     private String uuid;

    public ClientPayment() {
    }

	
    public ClientPayment(File file, int amountPaid, String receiptNumber, String uuid) {
        this.file = file;
        this.amountPaid = amountPaid;
        this.receiptNumber = receiptNumber;
        this.uuid = uuid;
    }
    public ClientPayment(User user, File file, int amountPaid, String receiptNumber, Date datePaid, String uuid) {
       this.user = user;
       this.file = file;
       this.amountPaid = amountPaid;
       this.receiptNumber = receiptNumber;
       this.datePaid = datePaid;
       this.uuid = uuid;
    }
   
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public File getFile() {
        return this.file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    public int getAmountPaid() {
        return this.amountPaid;
    }
    
    public void setAmountPaid(int amountPaid) {
        this.amountPaid = amountPaid;
    }
    public String getReceiptNumber() {
        return this.receiptNumber;
    }
    
    public void setReceiptNumber(String receiptNumber) {
        this.receiptNumber = receiptNumber;
    }
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


