package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Email generated by hbm2java
 */
public class Email  implements java.io.Serializable {


     private Integer emailId;
     private User user;
     private String emailRecipient;
     private String emailSubject;
     private String emailBody;
     private Date dateSent;

    public Email() {
    }

	
    public Email(User user, String emailRecipient, String emailSubject, Date dateSent) {
        this.user = user;
        this.emailRecipient = emailRecipient;
        this.emailSubject = emailSubject;
        this.dateSent = dateSent;
    }
    public Email(User user, String emailRecipient, String emailSubject, String emailBody, Date dateSent) {
       this.user = user;
       this.emailRecipient = emailRecipient;
       this.emailSubject = emailSubject;
       this.emailBody = emailBody;
       this.dateSent = dateSent;
    }
   
    public Integer getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(Integer emailId) {
        this.emailId = emailId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEmailRecipient() {
        return this.emailRecipient;
    }
    
    public void setEmailRecipient(String emailRecipient) {
        this.emailRecipient = emailRecipient;
    }
    public String getEmailSubject() {
        return this.emailSubject;
    }
    
    public void setEmailSubject(String emailSubject) {
        this.emailSubject = emailSubject;
    }
    public String getEmailBody() {
        return this.emailBody;
    }
    
    public void setEmailBody(String emailBody) {
        this.emailBody = emailBody;
    }
    public Date getDateSent() {
        return this.dateSent;
    }
    
    public void setDateSent(Date dateSent) {
        this.dateSent = dateSent;
    }




}


