package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EmpExpenditure generated by hbm2java
 */
public class EmpExpenditure  implements java.io.Serializable {


     private Integer expId;
     private Employee employee;
     private File file;
     private Date dateOfVisit;
     private int amountDrawn;
     private String destination;
     private Integer approvedBy;
     private Boolean status;
     private Integer balance;
     private Set transactionses = new HashSet(0);

    public EmpExpenditure() {
    }

	
    public EmpExpenditure(Employee employee, File file, int amountDrawn, String destination) {
        this.employee = employee;
        this.file = file;
        this.amountDrawn = amountDrawn;
        this.destination = destination;
    }
    public EmpExpenditure(Employee employee, File file, Date dateOfVisit, int amountDrawn, String destination, Integer approvedBy, Boolean status, Integer balance, Set transactionses) {
       this.employee = employee;
       this.file = file;
       this.dateOfVisit = dateOfVisit;
       this.amountDrawn = amountDrawn;
       this.destination = destination;
       this.approvedBy = approvedBy;
       this.status = status;
       this.balance = balance;
       this.transactionses = transactionses;
    }
   
    public Integer getExpId() {
        return this.expId;
    }
    
    public void setExpId(Integer expId) {
        this.expId = expId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public File getFile() {
        return this.file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    public Date getDateOfVisit() {
        return this.dateOfVisit;
    }
    
    public void setDateOfVisit(Date dateOfVisit) {
        this.dateOfVisit = dateOfVisit;
    }
    public int getAmountDrawn() {
        return this.amountDrawn;
    }
    
    public void setAmountDrawn(int amountDrawn) {
        this.amountDrawn = amountDrawn;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public Integer getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(Integer approvedBy) {
        this.approvedBy = approvedBy;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }




}


