package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0



/**
 * EntityConfig generated by hbm2java
 */
public class EntityConfig  implements java.io.Serializable {


     private Integer entityId;
     private String entityName;
     private String postalAddress;
     private int postalCode;
     private String locationName;
     private String entityEmail;
     private String phoneNo;
     private int nhifNo;
     private int nssfNo;
     private int vatNo;
     private int pinNo;
     private String uuid;

    public EntityConfig() {
    }

	
    public EntityConfig(String entityName, String postalAddress, int postalCode, String locationName, String phoneNo, int nhifNo, int nssfNo, int vatNo, int pinNo, String uuid) {
        this.entityName = entityName;
        this.postalAddress = postalAddress;
        this.postalCode = postalCode;
        this.locationName = locationName;
        this.phoneNo = phoneNo;
        this.nhifNo = nhifNo;
        this.nssfNo = nssfNo;
        this.vatNo = vatNo;
        this.pinNo = pinNo;
        this.uuid = uuid;
    }
    public EntityConfig(String entityName, String postalAddress, int postalCode, String locationName, String entityEmail, String phoneNo, int nhifNo, int nssfNo, int vatNo, int pinNo, String uuid) {
       this.entityName = entityName;
       this.postalAddress = postalAddress;
       this.postalCode = postalCode;
       this.locationName = locationName;
       this.entityEmail = entityEmail;
       this.phoneNo = phoneNo;
       this.nhifNo = nhifNo;
       this.nssfNo = nssfNo;
       this.vatNo = vatNo;
       this.pinNo = pinNo;
       this.uuid = uuid;
    }
   
    public Integer getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }
    public String getEntityName() {
        return this.entityName;
    }
    
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }
    public String getPostalAddress() {
        return this.postalAddress;
    }
    
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }
    public int getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(int postalCode) {
        this.postalCode = postalCode;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public String getEntityEmail() {
        return this.entityEmail;
    }
    
    public void setEntityEmail(String entityEmail) {
        this.entityEmail = entityEmail;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public int getNhifNo() {
        return this.nhifNo;
    }
    
    public void setNhifNo(int nhifNo) {
        this.nhifNo = nhifNo;
    }
    public int getNssfNo() {
        return this.nssfNo;
    }
    
    public void setNssfNo(int nssfNo) {
        this.nssfNo = nssfNo;
    }
    public int getVatNo() {
        return this.vatNo;
    }
    
    public void setVatNo(int vatNo) {
        this.vatNo = vatNo;
    }
    public int getPinNo() {
        return this.pinNo;
    }
    
    public void setPinNo(int pinNo) {
        this.pinNo = pinNo;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


