package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * File generated by hbm2java
 */
public class File  implements java.io.Serializable {


     private String fileCode;
     private CaseClasses caseClasses;
     private Instructions instructions;
     private Client client;
     private int fileId;
     private String notes;
     private Integer createdBy;
     private Date createdOn;
     private Integer modifiedBy;
     private Date modifiedOn;
     private String uuid;
     private Set empExpenditures = new HashSet(0);
     private Set clientPayments = new HashSet(0);
     private Set schedulers = new HashSet(0);
     private Set visits = new HashSet(0);
     private Set fileLendings = new HashSet(0);

    public File() {
    }

	
    public File(String fileCode, CaseClasses caseClasses, Instructions instructions, Client client, int fileId, String uuid) {
        this.fileCode = fileCode;
        this.caseClasses = caseClasses;
        this.instructions = instructions;
        this.client = client;
        this.fileId = fileId;
        this.uuid = uuid;
    }
    public File(String fileCode, CaseClasses caseClasses, Instructions instructions, Client client, int fileId, String notes, Integer createdBy, Date createdOn, Integer modifiedBy, Date modifiedOn, String uuid, Set empExpenditures, Set clientPayments, Set schedulers, Set visits, Set fileLendings) {
       this.fileCode = fileCode;
       this.caseClasses = caseClasses;
       this.instructions = instructions;
       this.client = client;
       this.fileId = fileId;
       this.notes = notes;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.modifiedBy = modifiedBy;
       this.modifiedOn = modifiedOn;
       this.uuid = uuid;
       this.empExpenditures = empExpenditures;
       this.clientPayments = clientPayments;
       this.schedulers = schedulers;
       this.visits = visits;
       this.fileLendings = fileLendings;
    }
   
    public String getFileCode() {
        return this.fileCode;
    }
    
    public void setFileCode(String fileCode) {
        this.fileCode = fileCode;
    }
    public CaseClasses getCaseClasses() {
        return this.caseClasses;
    }
    
    public void setCaseClasses(CaseClasses caseClasses) {
        this.caseClasses = caseClasses;
    }
    public Instructions getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(Instructions instructions) {
        this.instructions = instructions;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public int getFileId() {
        return this.fileId;
    }
    
    public void setFileId(int fileId) {
        this.fileId = fileId;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getEmpExpenditures() {
        return this.empExpenditures;
    }
    
    public void setEmpExpenditures(Set empExpenditures) {
        this.empExpenditures = empExpenditures;
    }
    public Set getClientPayments() {
        return this.clientPayments;
    }
    
    public void setClientPayments(Set clientPayments) {
        this.clientPayments = clientPayments;
    }
    public Set getSchedulers() {
        return this.schedulers;
    }
    
    public void setSchedulers(Set schedulers) {
        this.schedulers = schedulers;
    }
    public Set getVisits() {
        return this.visits;
    }
    
    public void setVisits(Set visits) {
        this.visits = visits;
    }
    public Set getFileLendings() {
        return this.fileLendings;
    }
    
    public void setFileLendings(Set fileLendings) {
        this.fileLendings = fileLendings;
    }




}


