package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * FileLending generated by hbm2java
 */
public class FileLending  implements java.io.Serializable {


     private Integer fileLendingId;
     private Employee employeeByLenderId;
     private File file;
     private Employee employeeByReceivedBy;
     private Location location;
     private Date dateOut;
     private Date dateIn;
     private String notes;
     private Integer createdBy;
     private Date createdOn;
     private Integer modifiedBy;
     private Date modifiedOn;
     private String uuid;

    public FileLending() {
    }

	
    public FileLending(Employee employeeByLenderId, File file, Date dateOut, String uuid) {
        this.employeeByLenderId = employeeByLenderId;
        this.file = file;
        this.dateOut = dateOut;
        this.uuid = uuid;
    }
    public FileLending(Employee employeeByLenderId, File file, Employee employeeByReceivedBy, Location location, Date dateOut, Date dateIn, String notes, Integer createdBy, Date createdOn, Integer modifiedBy, Date modifiedOn, String uuid) {
       this.employeeByLenderId = employeeByLenderId;
       this.file = file;
       this.employeeByReceivedBy = employeeByReceivedBy;
       this.location = location;
       this.dateOut = dateOut;
       this.dateIn = dateIn;
       this.notes = notes;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.modifiedBy = modifiedBy;
       this.modifiedOn = modifiedOn;
       this.uuid = uuid;
    }
   
    public Integer getFileLendingId() {
        return this.fileLendingId;
    }
    
    public void setFileLendingId(Integer fileLendingId) {
        this.fileLendingId = fileLendingId;
    }
    public Employee getEmployeeByLenderId() {
        return this.employeeByLenderId;
    }
    
    public void setEmployeeByLenderId(Employee employeeByLenderId) {
        this.employeeByLenderId = employeeByLenderId;
    }
    public File getFile() {
        return this.file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    public Employee getEmployeeByReceivedBy() {
        return this.employeeByReceivedBy;
    }
    
    public void setEmployeeByReceivedBy(Employee employeeByReceivedBy) {
        this.employeeByReceivedBy = employeeByReceivedBy;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Date getDateOut() {
        return this.dateOut;
    }
    
    public void setDateOut(Date dateOut) {
        this.dateOut = dateOut;
    }
    public Date getDateIn() {
        return this.dateIn;
    }
    
    public void setDateIn(Date dateIn) {
        this.dateIn = dateIn;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


