package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Instructions generated by hbm2java
 */
public class Instructions  implements java.io.Serializable {


     private String insCode;
     private int insId;
     private String insName;
     private String insDesc;
     private int insCharge;
     private Boolean status;
     private String uuid;
     private Set files = new HashSet(0);
     private Set schedulers = new HashSet(0);
     private Set visits = new HashSet(0);

    public Instructions() {
    }

	
    public Instructions(String insCode, int insId, String insName, String insDesc, int insCharge, String uuid) {
        this.insCode = insCode;
        this.insId = insId;
        this.insName = insName;
        this.insDesc = insDesc;
        this.insCharge = insCharge;
        this.uuid = uuid;
    }
    public Instructions(String insCode, int insId, String insName, String insDesc, int insCharge, Boolean status, String uuid, Set files, Set schedulers, Set visits) {
       this.insCode = insCode;
       this.insId = insId;
       this.insName = insName;
       this.insDesc = insDesc;
       this.insCharge = insCharge;
       this.status = status;
       this.uuid = uuid;
       this.files = files;
       this.schedulers = schedulers;
       this.visits = visits;
    }
   
    public String getInsCode() {
        return this.insCode;
    }
    
    public void setInsCode(String insCode) {
        this.insCode = insCode;
    }
    public int getInsId() {
        return this.insId;
    }
    
    public void setInsId(int insId) {
        this.insId = insId;
    }
    public String getInsName() {
        return this.insName;
    }
    
    public void setInsName(String insName) {
        this.insName = insName;
    }
    public String getInsDesc() {
        return this.insDesc;
    }
    
    public void setInsDesc(String insDesc) {
        this.insDesc = insDesc;
    }
    public int getInsCharge() {
        return this.insCharge;
    }
    
    public void setInsCharge(int insCharge) {
        this.insCharge = insCharge;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }
    public Set getSchedulers() {
        return this.schedulers;
    }
    
    public void setSchedulers(Set schedulers) {
        this.schedulers = schedulers;
    }
    public Set getVisits() {
        return this.visits;
    }
    
    public void setVisits(Set visits) {
        this.visits = visits;
    }




}


