package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * JobTitle generated by hbm2java
 */
public class JobTitle  implements java.io.Serializable {


     private int jobTitleId;
     private RoleMap roleMap;
     private String jobName;
     private int basicSalary;
     private Boolean active;
     private String uuid;
     private Set employees = new HashSet(0);

    public JobTitle() {
    }

	
    public JobTitle(int jobTitleId, RoleMap roleMap, String jobName, int basicSalary, String uuid) {
        this.jobTitleId = jobTitleId;
        this.roleMap = roleMap;
        this.jobName = jobName;
        this.basicSalary = basicSalary;
        this.uuid = uuid;
    }
    public JobTitle(int jobTitleId, RoleMap roleMap, String jobName, int basicSalary, Boolean active, String uuid, Set employees) {
       this.jobTitleId = jobTitleId;
       this.roleMap = roleMap;
       this.jobName = jobName;
       this.basicSalary = basicSalary;
       this.active = active;
       this.uuid = uuid;
       this.employees = employees;
    }
   
    public int getJobTitleId() {
        return this.jobTitleId;
    }
    
    public void setJobTitleId(int jobTitleId) {
        this.jobTitleId = jobTitleId;
    }
    public RoleMap getRoleMap() {
        return this.roleMap;
    }
    
    public void setRoleMap(RoleMap roleMap) {
        this.roleMap = roleMap;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public int getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(int basicSalary) {
        this.basicSalary = basicSalary;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


