package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int locationId;
     private String locationName;
     private String uuid;
     private Set branches = new HashSet(0);
     private Set schedulers = new HashSet(0);
     private Set fileLendings = new HashSet(0);
     private Set employees = new HashSet(0);
     private Set visits = new HashSet(0);

    public Location() {
    }

	
    public Location(int locationId, String locationName, String uuid) {
        this.locationId = locationId;
        this.locationName = locationName;
        this.uuid = uuid;
    }
    public Location(int locationId, String locationName, String uuid, Set branches, Set schedulers, Set fileLendings, Set employees, Set visits) {
       this.locationId = locationId;
       this.locationName = locationName;
       this.uuid = uuid;
       this.branches = branches;
       this.schedulers = schedulers;
       this.fileLendings = fileLendings;
       this.employees = employees;
       this.visits = visits;
    }
   
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set branches) {
        this.branches = branches;
    }
    public Set getSchedulers() {
        return this.schedulers;
    }
    
    public void setSchedulers(Set schedulers) {
        this.schedulers = schedulers;
    }
    public Set getFileLendings() {
        return this.fileLendings;
    }
    
    public void setFileLendings(Set fileLendings) {
        this.fileLendings = fileLendings;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getVisits() {
        return this.visits;
    }
    
    public void setVisits(Set visits) {
        this.visits = visits;
    }




}


