package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Locale generated by hbm2java
 */
public class Locale  implements java.io.Serializable {


     private int localesId;
     private String localeName;
     private String localeCode;
     private String uuid;
     private Set users = new HashSet(0);

    public Locale() {
    }

	
    public Locale(int localesId, String localeName, String localeCode, String uuid) {
        this.localesId = localesId;
        this.localeName = localeName;
        this.localeCode = localeCode;
        this.uuid = uuid;
    }
    public Locale(int localesId, String localeName, String localeCode, String uuid, Set users) {
       this.localesId = localesId;
       this.localeName = localeName;
       this.localeCode = localeCode;
       this.uuid = uuid;
       this.users = users;
    }
   
    public int getLocalesId() {
        return this.localesId;
    }
    
    public void setLocalesId(int localesId) {
        this.localesId = localesId;
    }
    public String getLocaleName() {
        return this.localeName;
    }
    
    public void setLocaleName(String localeName) {
        this.localeName = localeName;
    }
    public String getLocaleCode() {
        return this.localeCode;
    }
    
    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


