package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PersonName generated by hbm2java
 */
public class PersonName  implements java.io.Serializable {


     private Integer personNameId;
     private Person person;
     private String preffix;
     private String surname;
     private String firstName;
     private String otherName;
     private Integer createdBy;
     private Date createdOn;
     private Integer modifiedBy;
     private Date modifiedOn;
     private String uuid;

    public PersonName() {
    }

	
    public PersonName(Person person, String preffix, String surname, String firstName, String otherName, String uuid) {
        this.person = person;
        this.preffix = preffix;
        this.surname = surname;
        this.firstName = firstName;
        this.otherName = otherName;
        this.uuid = uuid;
    }
    public PersonName(Person person, String preffix, String surname, String firstName, String otherName, Integer createdBy, Date createdOn, Integer modifiedBy, Date modifiedOn, String uuid) {
       this.person = person;
       this.preffix = preffix;
       this.surname = surname;
       this.firstName = firstName;
       this.otherName = otherName;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.modifiedBy = modifiedBy;
       this.modifiedOn = modifiedOn;
       this.uuid = uuid;
    }
   
    public Integer getPersonNameId() {
        return this.personNameId;
    }
    
    public void setPersonNameId(Integer personNameId) {
        this.personNameId = personNameId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getPreffix() {
        return this.preffix;
    }
    
    public void setPreffix(String preffix) {
        this.preffix = preffix;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getOtherName() {
        return this.otherName;
    }
    
    public void setOtherName(String otherName) {
        this.otherName = otherName;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


