package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * PersonAttribute generated by hbm2java
 */
public class PersonAttribute  implements java.io.Serializable {


     private Integer personAttributeId;
     private IdentificationType identificationType;
     private Person personByNextOfKinId;
     private Person personByPersonId;
     private Integer idNumber;
     private String phoneNo;
     private String email;
     private String imageUrl;
     private Integer createdBy;
     private Date createdOn;
     private Integer modifiedBy;
     private Date modifiedOn;
     private String uuid;

    public PersonAttribute() {
    }

	
    public PersonAttribute(IdentificationType identificationType, Person personByPersonId, String uuid) {
        this.identificationType = identificationType;
        this.personByPersonId = personByPersonId;
        this.uuid = uuid;
    }
    public PersonAttribute(IdentificationType identificationType, Person personByNextOfKinId, Person personByPersonId, Integer idNumber, String phoneNo, String email, String imageUrl, Integer createdBy, Date createdOn, Integer modifiedBy, Date modifiedOn, String uuid) {
       this.identificationType = identificationType;
       this.personByNextOfKinId = personByNextOfKinId;
       this.personByPersonId = personByPersonId;
       this.idNumber = idNumber;
       this.phoneNo = phoneNo;
       this.email = email;
       this.imageUrl = imageUrl;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.modifiedBy = modifiedBy;
       this.modifiedOn = modifiedOn;
       this.uuid = uuid;
    }
   
    public Integer getPersonAttributeId() {
        return this.personAttributeId;
    }
    
    public void setPersonAttributeId(Integer personAttributeId) {
        this.personAttributeId = personAttributeId;
    }
    public IdentificationType getIdentificationType() {
        return this.identificationType;
    }
    
    public void setIdentificationType(IdentificationType identificationType) {
        this.identificationType = identificationType;
    }
    public Person getPersonByNextOfKinId() {
        return this.personByNextOfKinId;
    }
    
    public void setPersonByNextOfKinId(Person personByNextOfKinId) {
        this.personByNextOfKinId = personByNextOfKinId;
    }
    public Person getPersonByPersonId() {
        return this.personByPersonId;
    }
    
    public void setPersonByPersonId(Person personByPersonId) {
        this.personByPersonId = personByPersonId;
    }
    public Integer getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(Integer idNumber) {
        this.idNumber = idNumber;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


