package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer personId;
     private String gender;
     private Date dateOfBirth;
     private Integer createdBy;
     private String uuid;
     private Set clients = new HashSet(0);
     private Set personNames = new HashSet(0);
     private Set personAddresses = new HashSet(0);
     private Set personAttributesForPersonId = new HashSet(0);
     private Set employees = new HashSet(0);
     private Set personAttributesForNextOfKinId = new HashSet(0);
     private Set users = new HashSet(0);

    public Person() {
    }

	
    public Person(String gender, Date dateOfBirth, String uuid) {
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.uuid = uuid;
    }
    public Person(String gender, Date dateOfBirth, Integer createdBy, String uuid, Set clients, Set personNames, Set personAddresses, Set personAttributesForPersonId, Set employees, Set personAttributesForNextOfKinId, Set users) {
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.createdBy = createdBy;
       this.uuid = uuid;
       this.clients = clients;
       this.personNames = personNames;
       this.personAddresses = personAddresses;
       this.personAttributesForPersonId = personAttributesForPersonId;
       this.employees = employees;
       this.personAttributesForNextOfKinId = personAttributesForNextOfKinId;
       this.users = users;
    }
   
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }
    public Set getPersonNames() {
        return this.personNames;
    }
    
    public void setPersonNames(Set personNames) {
        this.personNames = personNames;
    }
    public Set getPersonAddresses() {
        return this.personAddresses;
    }
    
    public void setPersonAddresses(Set personAddresses) {
        this.personAddresses = personAddresses;
    }
    public Set getPersonAttributesForPersonId() {
        return this.personAttributesForPersonId;
    }
    
    public void setPersonAttributesForPersonId(Set personAttributesForPersonId) {
        this.personAttributesForPersonId = personAttributesForPersonId;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getPersonAttributesForNextOfKinId() {
        return this.personAttributesForNextOfKinId;
    }
    
    public void setPersonAttributesForNextOfKinId(Set personAttributesForNextOfKinId) {
        this.personAttributesForNextOfKinId = personAttributesForNextOfKinId;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


