package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * RoleMap generated by hbm2java
 */
public class RoleMap  implements java.io.Serializable {


     private Integer roleMapId;
     private Role roleByRoleThree;
     private Role roleByRoleTwo;
     private Role roleByRoleOne;
     private String uuid;
     private Boolean active;
     private String roleGroup;
     private Set jobTitles = new HashSet(0);

    public RoleMap() {
    }

	
    public RoleMap(String uuid) {
        this.uuid = uuid;
    }
    public RoleMap(Role roleByRoleThree, Role roleByRoleTwo, Role roleByRoleOne, String uuid, Boolean active, String roleGroup, Set jobTitles) {
       this.roleByRoleThree = roleByRoleThree;
       this.roleByRoleTwo = roleByRoleTwo;
       this.roleByRoleOne = roleByRoleOne;
       this.uuid = uuid;
       this.active = active;
       this.roleGroup = roleGroup;
       this.jobTitles = jobTitles;
    }
   
    public Integer getRoleMapId() {
        return this.roleMapId;
    }
    
    public void setRoleMapId(Integer roleMapId) {
        this.roleMapId = roleMapId;
    }
    public Role getRoleByRoleThree() {
        return this.roleByRoleThree;
    }
    
    public void setRoleByRoleThree(Role roleByRoleThree) {
        this.roleByRoleThree = roleByRoleThree;
    }
    public Role getRoleByRoleTwo() {
        return this.roleByRoleTwo;
    }
    
    public void setRoleByRoleTwo(Role roleByRoleTwo) {
        this.roleByRoleTwo = roleByRoleTwo;
    }
    public Role getRoleByRoleOne() {
        return this.roleByRoleOne;
    }
    
    public void setRoleByRoleOne(Role roleByRoleOne) {
        this.roleByRoleOne = roleByRoleOne;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public String getRoleGroup() {
        return this.roleGroup;
    }
    
    public void setRoleGroup(String roleGroup) {
        this.roleGroup = roleGroup;
    }
    public Set getJobTitles() {
        return this.jobTitles;
    }
    
    public void setJobTitles(Set jobTitles) {
        this.jobTitles = jobTitles;
    }




}


