package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Scheduler generated by hbm2java
 */
public class Scheduler  implements java.io.Serializable {


     private Integer schedulerId;
     private Employee employee;
     private File file;
     private Instructions instructions;
     private User user;
     private Location location;
     private Date dateFrom;
     private Date dateTo;
     private String notes;
     private Integer createdBy;
     private Date createdOn;
     private Integer modifiedBy;
     private Date modifiedOn;
     private String uuid;

    public Scheduler() {
    }

	
    public Scheduler(Employee employee, File file, Instructions instructions, User user, String uuid) {
        this.employee = employee;
        this.file = file;
        this.instructions = instructions;
        this.user = user;
        this.uuid = uuid;
    }
    public Scheduler(Employee employee, File file, Instructions instructions, User user, Location location, Date dateFrom, Date dateTo, String notes, Integer createdBy, Date createdOn, Integer modifiedBy, Date modifiedOn, String uuid) {
       this.employee = employee;
       this.file = file;
       this.instructions = instructions;
       this.user = user;
       this.location = location;
       this.dateFrom = dateFrom;
       this.dateTo = dateTo;
       this.notes = notes;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.modifiedBy = modifiedBy;
       this.modifiedOn = modifiedOn;
       this.uuid = uuid;
    }
   
    public Integer getSchedulerId() {
        return this.schedulerId;
    }
    
    public void setSchedulerId(Integer schedulerId) {
        this.schedulerId = schedulerId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public File getFile() {
        return this.file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    public Instructions getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(Instructions instructions) {
        this.instructions = instructions;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


