package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Utility generated by hbm2java
 */
public class Utility  implements java.io.Serializable {


     private Integer utilityId;
     private User user;
     private String utilityName;
     private String billCode;
     private Integer amount;
     private String receiptNo;
     private Date datePaid;
     private Date createdOn;

    public Utility() {
    }

	
    public Utility(User user, String utilityName, String receiptNo) {
        this.user = user;
        this.utilityName = utilityName;
        this.receiptNo = receiptNo;
    }
    public Utility(User user, String utilityName, String billCode, Integer amount, String receiptNo, Date datePaid, Date createdOn) {
       this.user = user;
       this.utilityName = utilityName;
       this.billCode = billCode;
       this.amount = amount;
       this.receiptNo = receiptNo;
       this.datePaid = datePaid;
       this.createdOn = createdOn;
    }
   
    public Integer getUtilityId() {
        return this.utilityId;
    }
    
    public void setUtilityId(Integer utilityId) {
        this.utilityId = utilityId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getUtilityName() {
        return this.utilityName;
    }
    
    public void setUtilityName(String utilityName) {
        this.utilityName = utilityName;
    }
    public String getBillCode() {
        return this.billCode;
    }
    
    public void setBillCode(String billCode) {
        this.billCode = billCode;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }




}


