package org.vetech.lrms.core.hibernate.models;
// Generated Feb 10, 2015 12:59:31 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Visit generated by hbm2java
 */
public class Visit  implements java.io.Serializable {


     private Integer visitId;
     private Employee employee;
     private Instructions instructions;
     private File file;
     private Location location;
     private Date startDate;
     private Date endDate;
     private Date estimatedTime;
     private Integer amount;
     private Integer createdBy;
     private Date createdOn;
     private Integer modifiedBy;
     private Date modifiedOn;
     private String uuid;

    public Visit() {
    }

	
    public Visit(Employee employee, Instructions instructions, File file, Location location, String uuid) {
        this.employee = employee;
        this.instructions = instructions;
        this.file = file;
        this.location = location;
        this.uuid = uuid;
    }
    public Visit(Employee employee, Instructions instructions, File file, Location location, Date startDate, Date endDate, Date estimatedTime, Integer amount, Integer createdBy, Date createdOn, Integer modifiedBy, Date modifiedOn, String uuid) {
       this.employee = employee;
       this.instructions = instructions;
       this.file = file;
       this.location = location;
       this.startDate = startDate;
       this.endDate = endDate;
       this.estimatedTime = estimatedTime;
       this.amount = amount;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.modifiedBy = modifiedBy;
       this.modifiedOn = modifiedOn;
       this.uuid = uuid;
    }
   
    public Integer getVisitId() {
        return this.visitId;
    }
    
    public void setVisitId(Integer visitId) {
        this.visitId = visitId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Instructions getInstructions() {
        return this.instructions;
    }
    
    public void setInstructions(Instructions instructions) {
        this.instructions = instructions;
    }
    public File getFile() {
        return this.file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getEstimatedTime() {
        return this.estimatedTime;
    }
    
    public void setEstimatedTime(Date estimatedTime) {
        this.estimatedTime = estimatedTime;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }
    
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


